http:
  host: "![mF+KHsYxA9gab+q2EbcCZg==]"
  port: "![tSi+GCzCuio=]"

database:
  host: "![mF+KHsYxA9gab+q2EbcCZg==]"
  port: "![YxqEABGajhk=]"
  user: "![yelZmzLGF18=]"
  password: "![OXrXLQzmmYjlmbBkXjbboVMlu1S1gS39]"